/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'COMPONENT__ERRORBOUNDARY-GLOBAL': typeof import('./src/components/COMPONENT__ERROR-BOUNDARY--GLOBAL.vue')['default']
    'COMPONENT__NOTIFICATION-CONTAINER': typeof import('./src/components/COMPONENT__NOTIFICATION--CONTAINER.vue')['default']
    'PAGE__HOME-DEFAULT': typeof import('./src/views/PAGE__HOME--DEFAULT.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
